frontend/controllers/CartController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

use frontend\components\Cart;
use common\models\Order;
use common\models\Item;
/**
 * Cart controller
 */
class CartController extends Controller
{

    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionAddItem() {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        extract($_POST);


        Cart::pushItem($itemId, $dateFrom, $dateTo);
        
        $item = Item::findOne($itemId);
        if ($item->isPsKonzola()) {
            Cart::pushItem(Item::DUALSHOCK_ID, $dateFrom, $dateTo);
        }

        if ($item->isXboxKonzola()) {
            Cart::pushItem(Item::XBOXCONTROLLER_ID, $dateFrom, $dateTo);
        }

        $cartItems = \Yii::$app->session->get('cart');

        return [
            'status'=>1,
            'cartItems'=>$cartItems
        ];

        return $cart;
    }

    public function actionRemoveItem() {
        $key = $_POST['cartKey'];

        Cart::removeByKey($key);

        echo json_encode(['status'=>1]);die();
    }

    public function actionCartBox() {
        return \frontend\widgets\CartBox::widget([]);
    }

    public function actionCheckout() {

        if (\Yii::$app->user->isGuest) {
            return $this->render('notLoggedIn', []);
        }
        
        $i = \Yii::$app->user->identity;

        $order = new Order;

        if (!isset($_POST['Order'])) {

            $profile = $i->profile;
            $order->street = $profile->street;
            $order->zip = $profile->zip;
            $order->city = $profile->city;

            $order->street = $profile->street;
            $order->zip = $profile->zip;
            $order->city = $profile->city;

            $order->otherStreet = $profile->otherStreet;
            $order->otherZip = $profile->otherZip;
            $order->otherCity = $profile->otherCity;

        } else {
            $order->setAttributes($_POST['Order']);
            $order->status = 'new';
            $order->userId = $i->id;

            $otherAddress = $order->otherStreet || $order->otherZip || $order->otherCity;
            

            if ($otherAddress && $order->deliveryType == 'courier' && !$order->otherDeliveryPriceId) 
                $order->addError('otherDeliveryPriceId', 'Ak je povinná doručovacia adresa, musí byť toto pole vyplnené');

            if ($otherAddress) {
                $order->deliveryPriceId = $order->otherDeliveryPriceId;
            }


            if ($order->deliveryType == 'courier' && !$order->deliveryPriceId) {
                $order->addError('deliveryPriceId', 'Pole je povinné');
            }

            if ($order->deliveryPriceId) $order->deliveryPrice = \common\models\DeliveryPrice::findOne($order->deliveryPriceId)->amount;


            $stats = Cart::getStats();
            
            $order->dateFrom = $stats['dateFrom'];
            $order->dateTo = $stats['dateTo'];

            $order->dateAdded = date('Y-m-d H:i:s');
            // vd($order->errors);
            

            if ($order->validate(null, false)) {

                return $this->render('confirm', [
                    'order'=>$order
                ]);

                $order->save();
                Cart::setOrderItems($order);
                $order->updateTotalPrice();
                Cart::reset();

                return $this->redirect(['/cart/thankyou']);
            } else {
                // this should not happen
                // vd($order->errors);
            }
        }

        return $this->render('checkout', [
            'order'=>$order,
            'otherAddress' => $order->otherStreet || $order->otherZip || $order->otherCity
            // 'cartContent'=> \frontend\components\Cart::getContent()
        ]);
    }


    public function actionSubmit() {
        if (isset($_POST['Order'])) {
            $order = new Order;
            $order->setAttributes($_POST['Order']);

            $order->save();
            Cart::setOrderItems($order);
            $order->updateTotalPrice();
            Cart::reset();

            $order->sendMail($order->user->email);
            
            return $this->redirect(['/cart/thankyou']);
        }
    }

    public function actionThankyou() {

        return $this->render('thankyou', []);

    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'cartContent'=> \frontend\components\Cart::getContent()
        ]);
    }

    public function actionGetStats() {
        $stats = Cart::getStats();

        echo json_encode($stats);
        die();
    }

    public function actionOrder() {

        $order = new Order;

        return $this->render('order', [
            'user'=>\Yii::$app->user->identity,
            'order'=>$order
        ]);

    }

    
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;

use common\components\Helpers;
use common\models\Item;
use common\models\LoginForm;

use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public $cId;
    public $rootCId;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionT() {
        $this->layout = 'empty';

        return $this->render('t', [
            'order'=>\common\models\Order::findOne(1)
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionXbox() {
        $cId = isset($_GET['cId']) ? $_GET['cId'] : 5;
        $this->cId = $cId;
        
        $this->rootCId = 2;        

        return $this->renderList($cId);
    }

    public function actionPlaystation() {

        $cId = isset($_GET['cId']) ? $_GET['cId'] : 3;
        $this->cId = $cId;
        $this->rootCId = 1;
        
        return $this->renderList($cId);
    }

    // toto zere datumy s bodkami !
    // ak niekto zada dateFrom neskor ako je dateTo, resp. dateTo skor ako je dateFrom, nastavi dateTo + 1 den po dateFrom
    private function setGlobalDates($dateFrom, $dateTo) {

        $dateFromTime = strtotime(Helpers::formatDateToDb($dateFrom));
        $dateToTime = strtotime(Helpers::formatDateToDb($dateTo));

        if ($dateToTime < $dateFromTime) {
            $datetime = new \DateTime(Helpers::formatDateToDb($dateFrom));
            $datetime->modify('+1 day');
            $dateTo = $datetime->format('d.m.Y H:i');
        }

        Yii::$app->session->set('dateFrom', $dateFrom);
        Yii::$app->session->set('dateTo', $dateTo);
    }

    public function getGlobalDateFrom() {
        if ($dateFrom = Yii::$app->session->get('dateFrom')) return $dateFrom;
        return date('d.m.Y H:i');
    }

    public function getGlobalDateTo() {
        if ($dateTo = Yii::$app->session->get('dateTo')) return $dateTo;
        $datetime = new \DateTime();
        $datetime->modify('+1 day');
        return $datetime->format('d.m.Y H:i');
    }

    public function renderList($cId) {

        if (isset($_GET['dateFrom']) && isset($_GET['dateTo'])) {
            $this->setGlobalDates($_GET['dateFrom'], $_GET['dateTo']);
        }

        $dateFrom = $this->getGlobalDateFrom();
        $dateTo = $this->getGlobalDateTo();

        $itemType = \common\models\ItemType::findOne($cId);
        if ($itemType->isLeaf()) {
            $itemTypeIds = [$itemType->id];
        } else {
            $leaves = $itemType->leaves()->all();
            
            $itemTypeIds = [];
            foreach ($leaves as $l) {
                $itemTypeIds[] = $l->id;
            }
        }

        $dateFromDb = Helpers::formatDateToDb($dateFrom);
        $dateToDb = Helpers::formatDateToDb($dateTo);

        $query = \common\models\Item::find();

        $query->andWhere('item.id IN (
            SELECT itemId FROM item_has_type WHERE itemTypeId IN ('.implode(',', $itemTypeIds).')
        )');

        $query->orderBy('name ASC');
        
        $itemsProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 9, // 3 riadky po 3
            ],
        ]);


        return $this->render('grid', [
            'itemsProvider'=>$itemsProvider,
            'cId'=>$cId,
            
            'dateFrom'=>$dateFrom,
            'dateTo'=>$dateTo,
            'dateFromDb'=>$dateFromDb,
            'dateToDb'=>$dateToDb
        ]);
    }

    
    public function actionDetail($id) {
        $item = Item::findOne($id);

        if (isset($_GET['dateFrom']) && isset($_GET['dateTo'])) {
            $this->setGlobalDates($_GET['dateFrom'], $_GET['dateTo']);
        }

        $dateFrom = $this->getGlobalDateFrom();
        $dateTo = $this->getGlobalDateTo();

        $dateFromDb = Helpers::formatDateToDb($dateFrom);
        $dateToDb = Helpers::formatDateToDb($dateFrom);

        return $this->render('detail', [
            'item'=>$item,

            'dateFrom'=>$dateFrom,
            'dateTo'=>$dateTo,

            'dateFromDb'=>$dateFromDb,
            'dateToDb'=>$dateToDb
        ]);
    }

    public function actionLogout() {
        \Yii::$app->user->logout();
        return $this->redirect(['/']);
    }
    
    public function actionONas() {
        return $this->render('about', [
        ]);
    }    

    public function actionVop() {
        return $this->render('policy', [
        ]);
    }

    public function actionKontakt() {
        return $this->render('kontakt', [
        ]);   
    }
}

frontend/views/cart/confirm.php
<?php 
use yii\helpers\Url;
use frontend\components\Cart;
use common\components\Helpers;

$stats = Cart::getStats();
$cartContent = Cart::getContent();
$user = \Yii::$app->user->identity;

$dt = Helpers::formatDateFromDb($stats['dateFrom']);
$dt = explode(' ', $dt);
?>

<style>
	#agreeForm label {
		font-weight:bold;font-size:20px; color:black !important;
	}

	#agreeForm label a {
		color:black !important;
		text-decoration:underline !important;
	}

	#agreeBox:hover {
		cursor:pointer;
	}
</style>

<form id="confirmForm" method="post" action="<?=Url::to(['cart/submit']);?>">
	<input type="hidden" name="Order[deliveryPriceId]" value="<?=$order->deliveryPriceId;?>"/>
	<input type="hidden" name="Order[street]" value="<?=$order->street;?>"/>
	<input type="hidden" name="Order[zip]" value="<?=$order->zip;?>"/>
	<input type="hidden" name="Order[city]" value="<?=$order->city;?>"/>
	<input type="hidden" name="Order[otherStreet]" value="<?=$order->otherStreet;?>"/>
	<input type="hidden" name="Order[otherZip]" value="<?=$order->otherZip;?>"/>
	<input type="hidden" name="Order[otherCity]" value="<?=$order->otherCity;?>"/>
	<input type="hidden" name="Order[deliveryType]" value="<?=$order->deliveryType;?>"/>
	<input type="hidden" name="Order[memo]" value="<?=$order->memo;?>"/>
	<input type="hidden" name="Order[status]" value="<?=$order->status;?>"/>
	<input type="hidden" name="Order[userId]" value="<?=$order->userId;?>"/>
	<input type="hidden" name="Order[deliveryPrice]" value="<?=$order->deliveryPrice;?>"/>
	<input type="hidden" name="Order[dateFrom]" value="<?=$order->dateFrom;?>"/>
	<input type="hidden" name="Order[dateTo]" value="<?=$order->dateTo;?>"/>
	<input type="hidden" name="Order[dateAdded]" value="<?=$order->dateAdded;?>"/>

<div class="container">
    <div class="page-header">
        <h2 class="page-title">Potvrdenie objednávky</h2>
        <!-- <p class="page-subtitle">DO eiusmod tempor incididunt ut labore et dolore magna aliqua</p> -->
    </div><!-- /.page-header -->

    <div class="page-body">

    	<table class="table table-cart cart-detail">
    		<thead>
	            <tr>
	                <th width="20%" class="dark">Názov</th>
	                <th width="40%"> Čas</th>
	                <th width="15%" class="dark text-center">Počet</th>
	                <th width="20%">Cena</th>
	            </tr>
	        </thead>
    	
    		<tbody class="cart-body-content">
        		<?php foreach ($cartContent as $i=>$data) { ?>
					<tr>
						<td>
                            <div class="media">
                                <div class="media-body">
                                    <h3 class="media-heading"><?=$data['item']->name;?></h3>
                                </div>
                            </div>
                        </td>

						<td>
							 od : <?=$data['dateFrom'];?> <br/>
							 do : <?=$data['dateTo'];?>
						</td>

						<td>
							<?=$data['count'];?> ks
						</td>

						<td>
							<?=Helpers::cuteNumber($data['price']);?> EUR
						</td>

					</tr>
				<?php } ?>

					<tr>
						<td>
                            Doprava - <?php if ($order->deliveryType == 'onplace') echo 'osobne'; ?>
                           <?php if ($order->deliveryType == 'courier') echo 'kuríer - '.\common\models\DeliveryPrice::findOne($order->deliveryPriceId)->name; ?>
                        </td>

						<td>
							<?=Helpers::formatDateFromDb($stats['dateFrom']);?>
						</td>

						<td>
							
						</td>

						<td>
							<?php 
								if ($order->deliveryType == 'courier') echo $order->deliveryPrice;
								if ($order->deliveryType == 'onplace') echo '0,00';
							?> EUR
						</td>

					</tr>
			</tbody>

    	</table>


    	<hr/>


    	<h3> Moje údaje </h3>

    	<address>
		  <strong> <?=$user->profile->name;?> </strong><br>
		  <?=$order->street;?><br>
		  <?=$order->zip;?> <?=$order->city;?><br>
		  <abbr title="Phone">P:</abbr> <?=$user->profile->phone;?>
		</address>

		<address>
		  <?=$user->email;?></address>
		</address>

		<hr/>

		<?php if ($order->deliveryType == 'onplace') { ?>
			<address>
				Objednávku si vyzdvihnem osobne na Obchodnej ulici č. 39 v Bratislave dňa <?=$dt[0];?> o <?=$dt[1];?>
			</address>
		<?php } ?>

		<?php if ($order->deliveryType == 'courier') { ?>
			<address>
				Objednávku mi doručí kuriér <?=$dt[0];?> o <?=$dt[1];?> na nasledujúcej adrese: <br/> <br/>

				<?php if ($order->hasOtherAddress()) { ?>
					<address>
					  <strong> <?=$user->profile->name;?> </strong><br>
					  <?=$order->otherStreet;?><br>
					  <?=$order->otherZip;?> <?=$order->otherCity;?><br>
					  <abbr title="Phone">P:</abbr> <?=$user->profile->phone;?>
					</address>
				<?php } else { ?>
					<address>
					  <strong> <?=$user->profile->name;?> </strong><br>
					  <?=$order->street;?><br>
					  <?=$order->zip;?> <?=$order->city;?><br>
					  <abbr title="Phone">P:</abbr> <?=$user->profile->phone;?>
					</address>
				<?php } ?> 
			</address>
		<?php } ?>


		<hr/>

		<address>		
			<?php 
				$sum = $stats['sum'];
				if ($order->deliveryType == 'courier') $sum+=$order->deliveryPrice;
			?>
			Celková cena objednávky je <?=Helpers::cuteNumber($sum);?> EUR, ktorú uhradím v hotovosti. Pri preberaní objednávky si <u>pripravím občiansky preukaz</u>.
		</address>

		<div class="col-md-12">
			<div class="checkout-checkbox-option pull-right" id="agreeForm">                                      
                <input type="checkbox" value="option2" id="optionsRadios" name="optionsRadios" class="book-radio">                                        
                <label for="optionsRadios" class="book-radio-label">
                    <span id="agreeBox" class="radio-background"><i class="icon fa fa-circle"></i></span> Súhlasím s <a href="<?=Url::to(['/site/vop']);?>">obchodnými podmienkami</a>
                </label>
            </div>
		</div>

	  	<div class="col-md-12">
            <button type="submit" id="checkoutBtn" class="pull-right btn btn-primary btn-checkout">
                Odoslať objednávku
                <i class="fa fa-chevron-right"></i>
            </button>
        </div>
    </div>
</div>

</form>
<?php $this->registerJsFile('@web/js/cart.js',['depends' => ["frontend\assets\AppAsset"]]); ?>

frontend/views/cart/index.php
<?php 
use yii\helpers\Url;
use frontend\components\Cart;

$stats = Cart::getStats();

$this->title = 'Košík'.' | Požičovňa hier | TKJHR.sk';

// vd($cartContent);
// Cart::reset();
?>
        <div class="cart page">
            <div class="container">
                <div class="page-header">
                    <h2 class="page-title">Košík</h2>
                    <p class="page-subtitle">K sume vašej objednávky, sa môže pripočítať cena za doručenie v ďaľšom kroku.</p>
                </div><!-- /.page-header -->

                <?php if (empty($cartContent)) { ?>
                         <div style="text-align:center; margin:50px" class="page-body">
                            <span style="text-transform: uppercase; font-size:32px; font-weight:bold"> Váš košík je prázdny </span>
                         </div>
                    <?php } else { ?>
                        <div class="page-body">
                            <div class="order-detail table-responsive">
                                


                                    <table class="table table-cart cart-detail ">
                                		 
                                        <thead>
                                            <tr>
                                                <th width="20%" class="dark">Názov</th>
                                                <th width="40%"> Čas</th>
                                                <th width="15%" class="dark text-center">Počet</th>
                                                <th width="20%">Cena</th>
                                                <th width="10%" class="dark">&nbsp;</th>
                                            </tr>
                                        </thead>
            							 
                                        <tbody class="cart-body-content">
            		                		<?php foreach ($cartContent as $i=>$data) { ?>
            									<tr>
            										<td>
            	                                        <div class="media">
            	                                            <div class="media-body">
            	                                                <h3 class="media-heading"><a href="<?=Url::to(['site/detail', 'id'=>$data['itemId']]);?>"><?=$data['item']->name;?></a></h3>
            	                                            </div>
            	                                        </div>
            	                                    </td>

            										<td>
            											 od : <?=$data['dateFrom'];?> <br/>
            											 do : <?=$data['dateTo'];?>
            										</td>

            										<td>
            											<input style="width:60px" type="text" value="<?=$data['count'];?>"/> ks
            										</td>

            										<td>
            											<?=$data['price'];?> EUR
            										</td>

            										<td>
            											<button class="btn btn-primary-light btn-flat removeItem" cart-item-id="<?=$data['key'];?>" type="button">X</button>
            										</td>

            									</tr>
            								<?php } ?>
            							</tbody>
            						</table>
                            </div><!-- /.order-detail -->
                            <div class="row">

                                <div class="col-xs-12 col-sm-6 center-sm pull-right">
                                    <div class="table-responsive">
                                        <table class="table table-cart">
                                            <tfoot>
                                                <tr>
                                                	<td>&nbsp;</td>
                                                    <td><i class="icon-chevron fa fa-chevron-right"></i>&nbsp;Suma:</td>
                                                    <td id="cartSum"><?=$stats['sum'];?> &euro;</td>
                                                </tr>
                                            </tfoot><!-- /tfoot -->
                                        </table><!-- /table -->
                                    </div><!-- /table-responsive -->
                                </div><!-- /.col -->
                                <div class="col-md-12">
                                        <a href="<?=Url::to(['cart/checkout']);?>" class="pull-right btn btn-primary btn-checkout">Pokračovat v objednávke &nbsp;<i class="fa fa-chevron-right"></i></a>
                                </div>

                            </div><!-- /.row -->
                        </div><!-- /.page-body -->
                <?php } ?> 
            </div><!-- /.container -->
        </div><!-- /.cart page -->            <a class="scrollup hidden-xs hidden-sm" href="#" style="display: inline;"><img src="assets/images/top-scroll.png" alt=""></a>

<?php $this->registerJsFile('@web/js/cart.js',['depends' => ["frontend\assets\AppAsset"]]); ?>

frontend/views/cart/notLoggedIn.php
<?php 
use yii\helpers\Url;
?>
<div class="container">
    <div class="center-block  not-found-page-content">
        <div class="page-header">
            
            <h2 class="page-title">Nie ste prihlásený</h2>
            
            <p class="page-subtitle">Ak chcete pokračovať v objednávke, musíte sa <a href="<?=Url::to(['/user/login']);?>">prihlásiť</a> alebo <a href="<?=Url::to(['/user/register']);?>">registrovať</a>.</p>
        </div><!-- /.page-header -->
    </div><!-- /.col -->            
</div>

frontend/views/cart/order.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model common\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>


<?= $form->field($order, 'deliveryType')->dropDownList(
    \common\models\Order::getDeliveryTypes() 
) ?>

<hr/>



<div class="form-group">
</div>

<?php ActiveForm::end(); ?>

frontend/views/cart/thankyou.php
<?php 
use yii\helpers\Url;
?>
<div class="container">
    <div class="center-block  not-found-page-content">
        <div class="page-header">
            
            <h2 class="page-title">Ďakujeme za Vašu objednávku</h2>
            
            <p class="page-subtitle"></p>
        </div><!-- /.page-header -->
    </div><!-- /.col -->            
</div>