backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller as BaseController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

   
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;

use common\components\Helpers;
use common\models\Item;
use common\models\LoginForm;

use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public $cId;
    public $rootCId;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionT() {
        $this->layout = 'empty';

        return $this->render('t', [
            'order'=>\common\models\Order::findOne(1)
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionXbox() {
        $cId = isset($_GET['cId']) ? $_GET['cId'] : 5;
        $this->cId = $cId;
        
        $this->rootCId = 2;        

        return $this->renderList($cId);
    }

    public function actionPlaystation() {

        $cId = isset($_GET['cId']) ? $_GET['cId'] : 3;
        $this->cId = $cId;
        $this->rootCId = 1;
        
        return $this->renderList($cId);
    }

    // toto zere datumy s bodkami !
    // ak niekto zada dateFrom neskor ako je dateTo, resp. dateTo skor ako je dateFrom, nastavi dateTo + 1 den po dateFrom
    private function setGlobalDates($dateFrom, $dateTo) {

        $dateFromTime = strtotime(Helpers::formatDateToDb($dateFrom));
        $dateToTime = strtotime(Helpers::formatDateToDb($dateTo));

        if ($dateToTime < $dateFromTime) {
            $datetime = new \DateTime(Helpers::formatDateToDb($dateFrom));
            $datetime->modify('+1 day');
            $dateTo = $datetime->format('d.m.Y H:i');
        }

        Yii::$app->session->set('dateFrom', $dateFrom);
        Yii::$app->session->set('dateTo', $dateTo);
    }

    public function getGlobalDateFrom() {
        if ($dateFrom = Yii::$app->session->get('dateFrom')) return $dateFrom;
        return date('d.m.Y H:i');
    }

    public function getGlobalDateTo() {
        if ($dateTo = Yii::$app->session->get('dateTo')) return $dateTo;
        $datetime = new \DateTime();
        $datetime->modify('+1 day');
        return $datetime->format('d.m.Y H:i');
    }

    public function renderList($cId) {

        if (isset($_GET['dateFrom']) && isset($_GET['dateTo'])) {
            $this->setGlobalDates($_GET['dateFrom'], $_GET['dateTo']);
        }

        $dateFrom = $this->getGlobalDateFrom();
        $dateTo = $this->getGlobalDateTo();

        $itemType = \common\models\ItemType::findOne($cId);
        if ($itemType->isLeaf()) {
            $itemTypeIds = [$itemType->id];
        } else {
            $leaves = $itemType->leaves()->all();
            
            $itemTypeIds = [];
            foreach ($leaves as $l) {
                $itemTypeIds[] = $l->id;
            }
        }

        $dateFromDb = Helpers::formatDateToDb($dateFrom);
        $dateToDb = Helpers::formatDateToDb($dateTo);

        $query = \common\models\Item::find();

        $query->andWhere('item.id IN (
            SELECT itemId FROM item_has_type WHERE itemTypeId IN ('.implode(',', $itemTypeIds).')
        )');

        $query->orderBy('name ASC');
        
        $itemsProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 9, // 3 riadky po 3
            ],
        ]);


        return $this->render('grid', [
            'itemsProvider'=>$itemsProvider,
            'cId'=>$cId,
            
            'dateFrom'=>$dateFrom,
            'dateTo'=>$dateTo,
            'dateFromDb'=>$dateFromDb,
            'dateToDb'=>$dateToDb
        ]);
    }

    
    public function actionDetail($id) {
        $item = Item::findOne($id);

        if (isset($_GET['dateFrom']) && isset($_GET['dateTo'])) {
            $this->setGlobalDates($_GET['dateFrom'], $_GET['dateTo']);
        }

        $dateFrom = $this->getGlobalDateFrom();
        $dateTo = $this->getGlobalDateTo();

        $dateFromDb = Helpers::formatDateToDb($dateFrom);
        $dateToDb = Helpers::formatDateToDb($dateFrom);

        return $this->render('detail', [
            'item'=>$item,

            'dateFrom'=>$dateFrom,
            'dateTo'=>$dateTo,

            'dateFromDb'=>$dateFromDb,
            'dateToDb'=>$dateToDb
        ]);
    }

    public function actionLogout() {
        \Yii::$app->user->logout();
        return $this->redirect(['/']);
    }
    
    public function actionONas() {
        return $this->render('about', [
        ]);
    }    

    public function actionVop() {
        return $this->render('policy', [
        ]);
    }

    public function actionKontakt() {
        return $this->render('kontakt', [
        ]);   
    }
}

frontend/views/site/_breadcrumbs.php
<?php 
    use yii\helpers\Url;
?>

<div class="breadcrumb-container">
	<div class="container">
		<ul class="breadcrumb pull-left">
			<li><a href="<?=Url::to(['/']);?>">Domov</a></li>
			<li><a href="<?=Url::to(['site/playstation']);?>">Playstation</a></li>
		</ul><!-- /.breadcrumb -->

		<!-- ========================================= BREADCRUMB SEARCH BOX ========================================= -->
		<ul class="list-unstyled search-box pull-right">
			<li data-target="#search" data-toggle="sub-header"><button type="button" class="btn btn-primary-dark search-button"><i class="fa fa-search icon"></i></button>
				<div class="row search-action sub-header" id="search">
				    <div class="col-sm-8 col-xs-12 no-padding-right">
				        <div class="input-group">
				            <span class="input-group-btn"><button class="btn btn-search" type="button"><i class="fa fa-search icon"></i></button></span>
				            <input type="text" class="form-control search-book" placeholder="Vyhladaj">
				        </div><!-- /.input-group -->
				    </div><!-- /.col -->
				    
				</div><!-- /.row -->
			</li>
		</ul><!-- /.search-box -->
		<!-- ========================================= BREADCRUMB SEARCH BOX : END ========================================= -->        

	</div><!-- /.container -->
</div><!-- /.breadcrumb-container -->

frontend/views/site/_leftMenu.php
<?php 
    use yii\helpers\Url;
    use common\models\ItemType;
?>
<div class="col-sm-4 col-sm-pull-8">
    <aside class="sidebar">
        <!-- ========================================= BOOK CATEGORY ========================================= -->
        <section class="module">
            <header class="module-header">
                <h4 class="module-book-category-title">Kategórie</h4>
            </header><!-- /.module-header -->

            <div class="module-body category-module-body">
                    
                <?php 
                    $rootNode = ItemType::findOne($this->context->rootCId);

                    $rootName = $rootNode->id == 1 ? 'playstation' : 'xbox';
                ?>

                <ul class="list-unstyled category-list">
                    

                    <?php foreach ($rootNode->children(1)->all() as $n=>$child) { ?>

                        <?php 
                            $subChildren = $child->children(1)->all();
                        ?>

                        <li class="<?=$cId == $child->id ? 'active' : '';?> <?=!empty($subChildren) ? 'sub-category-list':'';?>">
                            
                            <?php if ($cId != $child->id) { ?><a href="<?=Url::to(['site/'.$rootName, 'cId'=>$child->id]);?>"><?php } ?>
                                <?=$child->name;?>
                            <?php if ($cId != $child->id) { ?></a><?php } ?>

                            <?php if (!empty($subChildren)) { ?>
                                <ul class="list-unstyled">
                                    <?php foreach ($subChildren as $n=>$subChild) { ?>
                                        <li class="<?=$cId == $subChild->id ? 'active' : '';?>">

                                            <?php if ($cId != $subChild->id) { ?><a href="<?=Url::to(['site/'.$rootName, 'cId'=>$subChild->id]);?>"><?php } ?>
                                                <?=$subChild->name;?>
                                            <?php if ($cId != $subChild->id) { ?></a><?php } ?>

                                        </li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </li>

                    <?php } ?>


                    <!-- <li><a href="category.html">PS Vita</a></li> -->
                    <!-- <li><a href="category.html">Iné</a></li> -->
                </ul><!-- /.list-unstyled -->
            </div><!-- /.module-body -->
        </section><!-- /.module -->
        <!-- ========================================= BOOK CATEGORY : END ========================================= -->                    
    </aside><!-- /.sidebar -->
</div><!-- /.col -->

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */


$this->title = 'O nás'.' | Požičovňa hier | TKJHR.sk';

use yii\helpers\Html;
?>

<div class="container">
    <div class="row">
    	
    	<div class="col-md-12">
	    	<div class="page-header book-detail-header">
	    		<h1 class="book-title">O nás</h1>
	    	</div>

	    	<div class="page-body">

		    	<div class="book-detail-header">
		    		<p>
			    		Sme prvá požičovňa herných konzol, videohier a herného príslušenstva na Slovensku fungujúca od roku 2016. Okrem prenájmu herného sortimentu, máte odteraz aj možnosť prísť si zahrať obľúbené hry do baru na Obchodnej 39, alebo sa zúčastniť rôznych turnajov a športových / filmových prenosov. Vďaka našim službám už viac nemusíte večer zaspať od nudy, ani ísť na chatu či hotel bez hernej konzoly a tých najlepších hier. Taká je hra.
		    		</p>
		            
	        	</div>
	    	</div>	
    	</div>
    </div>      
</div>

frontend/views/site/detail.php
<?php 
    use yii\helpers\Url;

    use \frontend\components\Cart;
    use \common\components\Helpers;

    use kartik\growl\GrowlAsset;
    use kartik\base\AnimateAsset;
    
    GrowlAsset::register($this);
    AnimateAsset::register($this);


    $this->title = $item->name.' | Požičovňa hier | TKJHR.sk';
?>

<!-- toto neviem este -->
<input type="hidden" id="dateFromInput" value="<?=$dateFrom;?>"/>
<input type="hidden" id="dateToInput"  value="<?=$dateTo;?>"/>
<!--  -->


<div class="book-detail page">
<div class="container">
    <div class="primary-block clearfix">
        <div class="row">
            <div class="col-sm-4">
                <div class="book-cover book detail-book-cover">


                    <?php 
                        if ($item->detailThumbnailPath) {
                            $thumb = $item->detailThumbnailPath;
                        } else {
                            $thumb = Url::to(['/']).'images/empty-detail.png';
                        }
                    ?>
                    <img src="<?=$thumb;?>" class="img-responsive" alt="">

                    <div class="fade"></div>
                </div><!-- /.book-cover -->
            </div><!-- /.col -->

            <div class="col-sm-8">
                <div class="book-detail-header" style="margin-bottom:12px">
                    <h2 class="book-title"><?=$item->name;?></h2>
                    <p class="book-author">
                        <span class="book-author-name">
                            <?php 

                                $days = Cart::getDays($dateFrom, $dateTo);
                                $word = 'dní';
                                if ($days == 1) $word = 'deň';
                                if ($days == 2) $word = 'dni';
                                if ($days == 3) $word = 'dni';
                                if ($days == 4) $word = 'dni';

                                echo 'Cena je za '.$days.' '.$word;

                                if (Cart::isEvening($dateFrom)) echo ' pri prevzatí vo večerných hodinách (22:00 - 8:00)';
                            ?>
                        </span>
                        </p>
                </div><!-- /.book-detail-header -->

                <div class="book-detail-body">

                     <div class="row" style="margin-bottom:12px">
                        <form id="datechangeform" method="get" action="<?=Url::to(['site/detail']);?>">
                            <input type="hidden" name="id" value="<?=$item->id;?>"/>
                            <div class="col-md-6 col-sm-5">
                                <?php 
                                echo '<label class="control-label">Dátum prevzatia</label>';
                                echo \kartik\datetime\DateTimePicker::widget([
                                    'name' => 'dateFrom',
                                    'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                    'value' => $dateFrom,
                                    'options'=>['id'=>'dateFromInput'],
                                    'pluginOptions' => [
                                        'minuteStep' => 30,
                                        'autoclose'=>true,
                                        'format' => 'dd.mm.yyyy hh:ii'
                                    ]
                                ]);

                                ?>
                            </div><!-- /.col -->
                            <div class="col-md-6 col-sm-5">
                                <?php 
                                echo '<label class="control-label">Dátum vrátenia</label>';
                                echo \kartik\datetime\DateTimePicker::widget([
                                    'name' => 'dateTo',
                                    'options'=>['id'=>'dateToInput'],
                                    'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                    'value' => $dateTo,
                                    'pluginOptions' => [
                                        'autoclose'=>true,
                                        'format' => 'dd.mm.yyyy hh:ii'
                                    ]
                                ]);

                                ?>
                            </div><!-- /.col -->
                        </form>
                    </div>

                    <div class="detail-cart-button row clearfix">
                        <div class="pull-left col-md-6 col-sm-5 col-xs-12">
                            <div class="detail-book-price">
                                <span class="price">
                                
                                     <?php 
                                       echo Helpers::cuteNumber(Cart::calculateItemPrice($item, $dateFrom, $dateTo, 1));
                                     ?> &euro;

                                </span>
                            </div><!-- /.detail-book-price -->
                        </div><!-- /.pull-left -->

                        <div class="pull-right col-md-6 col-sm-7 col-xs-12">

                            <div class="row product-actions">                            
                                <?php if ($item->isAvailable($dateFromDb, $dateToDb)) { ?>
                                <a href="javascript:void(0)" item-id="<?=$item->id;?>" class="col-sm-6 btn btn-primary btn-addToCart addToCart"><i class="icon-plus fa fa-plus-circle"></i>Do košíka</a>
                                <div class="quantity book-detail-quantity col-xs-4 col-lg-3">  
                                                              
                                </div><!-- /.col -->   
                                <?php } else { ?>
                                <div class="quantity book-detail-quantity col-xs-12">  
                                    <div style="margin-top:10px" class="quantity-block">          
                                        <span class="alert alert-danger">Tovar nie je v uvedenom čase dostupný</span>
                                    </div>
                                </div>
                                <?php } ?>
                            </div><!-- /.row -->    
                        </div><!-- /.pull-right -->
                    </div><!-- /.detail-cart-button -->

                    <div class="clearfix"></div>

                    <div class="product-description">
                        <h3>O hre</h3>
                        <p>
                            <?=$item->text;?>
                        </p>
                    </div><!-- /.product-description -->

                </div><!-- /.book-detail-body -->
            </div><!-- /.col -->
        </div><!-- /.row -->

    </div><!-- /.primary-block -->
</div><!-- /.container -->

</div><!-- /.book-detail page -->
<a class="scrollup hidden-xs hidden-sm" href="#" style="display: inline;"><img src="<?=Url::to(['/']);?>images/top-scroll.png" alt=""></a>

<?php $this->registerJsFile('@web/js/cart.js',['depends' => ["frontend\assets\AppAsset"]]); ?>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<div class="container">
    <div class="center-block  not-found-page-content">
        <div class="page-header">
            <h2 class="page-title">HUPS, <?= nl2br(Html::encode($message)) ?></h2>
            <p class="page-subtitle"><?=$this->title;?></p>
        </div><!-- /.page-header -->
    </div><!-- /.col -->            
</div>

frontend/views/site/grid.php
<?php 
    use yii\helpers\Url;
    
    use \frontend\components\Cart;
    use \common\components\Helpers;

    use kartik\growl\GrowlAsset;
    use kartik\base\AnimateAsset;
    
    GrowlAsset::register($this);
    AnimateAsset::register($this);

    $this->title = ($this->context->rootCId == 1 ? 'Playstation 4' : 'XBOX One').' | Požičovňa hier | TKJHR.sk';

?>
<style>
.book-details .book-title {
    height: 73px;
}

@media screen and (max-width: 660px) {
    #searchBtnDiv {
        margin:auto;
        padding-top:40px;
        text-align:center;
    }
}

</style>
<div class="category page">
    <div class="container">
        <div class="page-header category-page-header">
            <h2 class="page-title"><?=$this->context->rootCId == 1 ? 'Playstation 4' : 'XBOX One';?></h2>
            <p class="page-subtitle">

                    Cena je za 

                    <?php 
                    $days = Cart::getDays($dateFrom, $dateTo);
                    $word = 'dní';
                    if ($days == 1) $word = 'deň';
                    if ($days == 2) $word = 'dni';
                    if ($days == 3) $word = 'dni';
                    if ($days == 4) $word = 'dni';

                    echo $days.' '.$word;
                    if (Cart::isEvening($dateFrom)) echo ' pri prevzatí vo večerných hodinách (22:00 - 8:00)';
                    ?>
            </p>
        </div>

        <div class="page-body">
            <div class="row">
                <!-- ========================================= CONTENT ========================================= -->
                <div class="col-sm-8 col-sm-push-4">
                    <div class="category-toolbar">
                        <div class="row">
                            <form id="datechangeform" method="get">
                            <input type="hidden" name="cId" value="<?=$cId;?>"/>
                            <div class="col-md-5 col-sm-5">
                                <?php 
                                echo '<label class="control-label">Dátum prevzatia</label>';
                                echo \kartik\datetime\DateTimePicker::widget([
                                    'name' => 'dateFrom',
                                    'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                    'value' => $dateFrom,
                                    'options'=>['id'=>'dateFromInput'],
                                    'pluginOptions' => [
                                        'minuteStep' => 30,
                                        'autoclose'=>true,
                                        'format' => 'dd.mm.yyyy hh:ii'
                                    ]
                                ]);

                                ?>
                            </div><!-- /.col -->


                            <div class="col-md-5 col-sm-5">
                                <?php 
                                echo '<label class="control-label">Dátum vrátenia</label>';
                                echo \kartik\datetime\DateTimePicker::widget([
                                    'name' => 'dateTo',
                                    'options'=>['id'=>'dateToInput'],
                                    'type' => \kartik\datetime\DateTimePicker::TYPE_COMPONENT_APPEND,
                                    'value' => $dateTo,
                                    'pluginOptions' => [
                                        'autoclose'=>true,
                                        'format' => 'dd.mm.yyyy hh:ii'
                                    ]
                                ]);

                                ?>
                            </div><!-- /.col -->
                            
                            <div id="searchBtnDiv" class="col-md-2 col-sm-12">
                                <label class="control-label">&nbsp;</label>
                                <input type="submit" class="btn btn-primary" value="Vyhladaj"/>
                            </div>
                            </form>

                        </div><!-- /.row -->
                    </div><!-- /.category-toolbar -->

                    <div class="tab-content">
                        <div role="tabpanel" id="grid" class="tab-pane active">
                            <div class="category-books books grid-view">
                                <div class="row">
                                        

                                    <?php foreach ($itemsProvider->getModels() as $model) { ?>
                                    <div class="col-md-4 col-sm-6">

                                        <div class="book">      
                                            <div class="book-cover">
                                                <div class="book-inner">
                                                    <?php 
                                                        if ($model->thumbnailPath) {
                                                            $thumb = $model->thumbnailPath;
                                                        } else {
                                                            $thumb = Url::to(['/']).'images/empty-detail.png';
                                                        }
                                                    ?>
                                                    <img width="193" height="261" alt="" src="<?=$thumb;?>">
                                                    <div class="fade"></div>
                                                    <div class="book-price">

                                                        <span class="price">
                                                             <?php 
                                                               echo Helpers::cuteNumber(Cart::calculateItemPrice($model, $dateFrom, $dateTo, 1));
                                                             ?> &euro;
                                                             
                                                        </span>

                                                    </div><!-- /.book-price -->

                                                    <?php if ($model->isAvailable($dateFromDb, $dateToDb)) { ?>
                                                    <div class="cart animate-effect">
                                                        <div class="action">
                                                            <a title="Add to Cart" href="javascript:void(0);" item-id="<?=$model->id;?>" class="add-to-cart addToCart">
                                                                <i class="icon icon-plus fa fa-plus-circle"></i>
                                                            </a>
                                                            <!-- <a title="Favourite" href="#" class="add-to-cart">
                                                                <i class="icon icon-heart fa fa-heart"></i>
                                                            </a>-->
                                                        </div><!-- /.action -->
                                                    </div><!-- /.cart -->
                                                    <?php } ?>
                                                </div><!-- /.book-inner -->
                                            </div><!-- /.book-cover -->


                                            <div class="book-details">
                                                <h3 class="book-title"><a href="<?=Url::to(['site/detail', 'id'=>$model->id]);?>"><?=$model->name;?></a></h3>
                                                

                                                <p class="book-author">
                                                    <?php if ($model->isAvailable($dateFromDb, $dateToDb)) { ?>
                                                        dostupné
                                                    <?php } else { ?>                                                    
                                                        nedostupné
                                                    <?php } ?>
                                                </p>
                                                
                                                <!--<div class="star-rating">
                                                    <i class="fa fa-star color"></i>
                                                    <i class="fa fa-star color"></i>
                                                    <i class="fa fa-star color"></i>
                                                    <i class="fa fa-star color"></i>
                                                    <i class="fa fa-star "></i>
                                                </div>-->
                                                <!-- /.star-rating -->

                                            </div><!-- /.book-details -->
                                        </div>

                                    </div>
                                    <?php } ?>

                                </div>
                            </div>
                        </div><!-- /.category-books -->
                    </div>

                        <?php 
                            echo \yii\widgets\LinkPager::widget([
                                'pagination'=>$itemsProvider->pagination,
                                'options' => ['class'=>'pagination book-pagination'],
                                'nextPageLabel'=>false,
                                'prevPageLabel'=>false,
                            ]);
                        ?>
                    </div>
                <!-- ========================================= SIDEBAR ========================================= -->
                <?php echo $this->context->renderPartial('_leftMenu', ['cId'=>$cId]);?>
                <!-- ========================================= SIDEBAR :END ========================================= -->
                
                </div>

            </div><!-- /.row -->
        </div><!-- /.page-body -->
    </div><!-- /.container -->
</div><!-- /.category page -->

<a class="scrollup hidden-xs hidden-sm" href="#" style="display: none;"><img src="<?=Url::to(['/']);?>images/top-scroll.png" alt=""></a>
<?php $this->registerJsFile('@web/js/cart.js',['depends' => ["frontend\assets\AppAsset"]]); ?>

frontend/views/site/index.php
<?php 
    use yii\helpers\Url;

    $this->title = 'Požičovňa konzol a hier | TKJHR.sk';
?>
<style>
#pchoose a {

}
</style>
<div class="container">
    <div class="" style="max-width:820px;text-align:center;margin:auto">
        <div class="page-header">
            <h2 class="page-title">&nbsp;</h2>
            <p class="page-subtitle">Vyber si platformu</p>
        </div><!-- /.page-header -->

        <div class="page-body">

          <div id="pchoose" class="row">
            <div class="col-md-6">
                <a href="<?=Url::to(['site/playstation']);?>">
                  <img class="front-page-image" src="<?=Url::to(['/']);?>images/ps.png"/><br/>
                </a>
                <a href="<?=Url::to(['site/playstation']);?>" class="btn btn-primary btn-lg"> 
                  PlayStation 4 
                </a>  
            </div>
            <div class="col-md-6">
                <a href="<?=Url::to(['site/playstation']);?>"> 
                  <img class="front-page-image" src="<?=Url::to(['/']);?>images/xbox.png"/><br/>
                </a>
                <a href="<?=Url::to(['site/xbox']);?>" class="btn btn-primary btn-lg"> 
                  XBOX One 
                </a>  
            </div>
          </div>

          <br/><br/><br/><br/>
        </div>
    </div>


   
</div>